fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: App\Entity\Authentication\User
    from_email:
        address: "noreply@parabot.org"
        sender_name: "Parabot"
