version: '3.7'

services:
  db:
    image: mariadb/server:10.3
    volumes:
      - ./database:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    restart: always

  php:
    build: ./php-fpm
    ports:
      - "9000:9001"
    volumes:
      - ../:/var/www/symfony:cached
    links:
      - db
    extra_hosts:
      - "db.dockit.site:127.0.0.1"

  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    links:
      - php
    volumes:
      - ../:/var/www/symfony:cached
    depends_on:
      - db
